on:
  rss:
    url:
      - https://www.gamedeveloper.com/rss.xml
      - https://www.thinkaloud.cc/rss/feed.xml
      - https://www.tuzei8.com/rss/index.rss
      - https://www.sqlsec.com/atom.xml
      - https://liqi.io/index.xml
      - https://tingtalk.me/atom.xml
      - https://xinquji.com/rss
      - https://blog.codingnow.com/atom.xml
      - https://xinquji.com/rss
      - https://pandaqr.github.io/feed.xml
      - https://anyway.fm/rss.xml
      - https://wangyurui.com/feed.xml
      - https://biopolyhedron.github.io/atom.xml
      - https://coolshell.cn/feed
      - https://www.voicer.me/feed
      - https://hypebeast.cn/feed
      - https://headsalon.org/feed
      - https://www.biede.com/feed/
      - http://www.hexieshe.com/feed
      - https://www.waerfa.com/feed
      - http://www.chuapp.com/feed
      - https://www.agilealliance.org/feed
      - http://feed.wxwenku.com/a/3366/feed
      - http://www.gamelook.com.cn/feed
      - https://youxiputao.com/feed


      - http://www.gamelook.com.cn/feed
      - http://youxiputao.com/feed
      - http://www.youxituoluo.com/feed
      - http://gamerboom.com/feed
      - http://www.yxzzd.com/feed
      - http://game.yesky.com/index.xml
      - http://www.people.com.cn/rss/game.xml
      - http://sspai.me/feed
      - https://www.dgtle.com/rss/dgtle.xml
      - http://www.36kr.com/feed
      - http://www.ithome.com/rss/
      - http://chinese.engadget.com/rss.xml
      - http://www.fortunechina.com/rss/management.xml


      - http://www.hexieshe.com/feed
      - http://www.dapenti.com/blog/rss2.asp
      - http://tomorrowsci.com/feed/
      - http://a-chien.blogspot.com/feeds/posts/default
      - http://www.cw.com.tw/RSS/cw_content.xml
      - http://www.gvm.com.tw/RSS/rss.asp

      - http://www.changhai.org/feed.xml
      - http://www.voicer.me/feed

jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://cubox.pro/c/api/save/a1xjIVcNHus
          method: POST
          body: |
            {
              "type":"url",
              "content":"${{ on.rss.outputs.link }}", 
              "title": "${{ on.rss.outputs.title }}",
              "folder":"RSS"
            }
